services:
  webapp:
    profiles:
      - setup
      - running
    image: boatflix_webapp
    container_name: webapp
    build:
      context: .
      dockerfile: dockerfiles/webapp.Dockerfile
    volumes:
      - ./webapp:/app
    ports:
      - 8080:8080
    networks:
      - boatflix
    logging: &logging
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"

  spotdl:
    profiles:
      - running
    image: boatflix_spotdl
    build:
      context: .
      dockerfile: dockerfiles/spotdl.Dockerfile
    container_name: spotdl
    volumes:
      - /data/media/Music:/music
      - /data/configs/spotdl/playlists:/app/playlists
      - /data/configs/spotdl/config.json:/root/.spotdl/config.json
    environment:
      - PORT=5050
      - HOST=0.0.0.0
    ports:
      - 5050:5050
    networks:
      - boatflix
    logging:
      *logging

  jellyseerr:
    profiles:
      - running
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
    volumes:
      - /data/configs/jellyseerr/config:/app/config
    restart: always
    ports:
      - 5055:5055
    networks:
      - boatflix
    logging:
      *logging

  jellyfin:
    profiles:
      - running
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file:
      - .env
    volumes:
      - /data/configs/jellyfin/config:/config
      - /data/media/Shows:/data/Shows
      - /data/media/Movies:/data/Movies
      - /data/media/Music:/data/Music
      - /data/media/Books:/data/Books
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900
    networks:
      - boatflix
    logging:
      *logging

  prowlarr:
    profiles:
      - running
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - /data/configs/prowlarr:/config
      - /data/media:/mnt/media
      - /data/media/Downloads:/mnt/downloads
    depends_on:
      flaresolverr:
        condition: service_started
    env_file:
      - .env
    ports:
      - 9696:9696
    healthcheck:
      test: ["CMD", "curl", "-fsL", "ipconfig.me"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
    networks:
      - boatflix
    logging:
      *logging

  flaresolverr:
    profiles:
      - running
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file:
      - .env
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    healthcheck:
      test: ["CMD", "curl", "-fsL", "ipconfig.me"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
    networks:
      - boatflix
    logging:
      *logging

  qbittorrent:
    profiles:
      - running
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:vpn"
    volumes:
      - /data/configs/qbittorrent:/config
      - /data/media/Downloads:/mnt/downloads
    env_file:
      - .env
    environment:
      - WEBUI_PORT=8081
    depends_on:
      vpn:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-fsL", "ipconfig.me"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
    logging:
      *logging

  lidarr:
    profiles:
      - running
    image: linuxserver/lidarr
    container_name: lidarr
    volumes:
      - /data/configs/lidarr:/config
      - /data/media:/mnt/media
      - /data/media/Downloads:/mnt/downloads
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fsL", "ipconfig.me"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
    ports:
      - 8686:8686
    networks:
      - boatflix
    logging:
      *logging

  radarr:
    profiles:
      - running
    image: linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /data/configs/radarr:/config
      - /data/media/Movies:/movies
      - /data/media/Downloads:/mnt/downloads
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fsL", "ipconfig.me"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
    ports:
      - 7878:7878
    networks:
      - boatflix
    logging:
      *logging

  readarr:
    profiles:
      - running
    image: linuxserver/readarr:develop
    container_name: readarr
    volumes:
      - /data/configs/readarr:/config
      - /data/media/Books:/mnt/books
      - /data/media/Downloads:/mnt/downloads
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fsL", "ipconfig.me"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
    ports:
      - 8787:8787
    networks:
      - boatflix
    logging:
      *logging

  calibrie:
    profiles:
      - running
    image: linuxserver/calibre:latest
    container_name: calibri
    volumes:
      - /data/configs/calibri:/config
      - /data/media/Books:/mnt/books
    env_file:
      - .env
    environment:
      - CUSTOM_PORT=8811
    ports:
      - 8811:8811
    healthcheck:
      test: ["CMD", "curl", "-fsL", "ipconfig.me"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
    networks:
      - boatflix
    logging:
      *logging

  sonarr:
    profiles:
      - running
    image: linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /data/configs/sonarr:/config
      - /data/media/Shows:/mnt/media/shows
      - /data/media/Downloads:/mnt/downloads
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fsL", "ipconfig.me"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
    ports:
      - 8989:8989
    networks:
      - boatflix
    logging:
      *logging

  bazarr:
    profiles:
      - running
    image: linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - /data/configs/bazarr:/config
      - /data/media:/mnt/media
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fsL", "ipconfig.me"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
    ports:
      - 6767:6767
    networks:
      - boatflix
    logging:
      *logging

  vpn:
    profiles:
      - running
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /data/configs/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - SERVER_REGIONS=Netherlands
    ports:
      - 8081:8081 # qBittorrent Web UI port
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
    networks:
      - boatflix
    restart: unless-stopped
    logging:
      *logging

  raspap:
    profiles:
      - setup
      - running
    container_name: raspap
    image: ghcr.io/raspap/raspap-docker:latest
    privileged: true
    network_mode: host
    cgroup: host # uncomment when using an ARM device
    environment:
      - RASPAP_SSID=boatflix
      - RASPAP_SSID_PASS=boatflix
      - RASPAP_COUNTRY=GB
      - RASPAP_WEBGUI_USER=${AP_USER}
      - RASPAP_WEBGUI_PASS=${AP_PASS}
      - RASPAP_WEBGUI_PORT=99
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    restart: unless-stopped
    logging:
      *logging

networks:
  boatflix:
    driver: bridge
